### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [Binary-Kitchen/doorlock-app#6]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by rralf** [comment]
Everything relevant (for developers) can be found in `git log`, everything else in https://github.com/Binary-Kitchen/doorlock-app/blob/master/app/src/main/play/en-GB/whatsnew . So why would we need a CHANGELOG?

**Comment by rckTom** [comment]
Closed because of no response.

**Comment by leela52452** [comment]
one and only one reason
https://keepachangelog.com

**Comment by rralf** [comment]
Again, we do have that. From the user's perspective, take a look at the whatsnew. From the developer's perspective, look at the git history. Pointing me out to some website won't convince me.
